### PR TITLE
Small Fixes

### PR DESCRIPTION
**Pull request by createme**
-Color for SuperSU and Tunein
-Cut off shadow in the Unicon Icon

### CODE REVIEW

**Comment by crutchcorn** [comment]
Thank you. @createme, what is your real name?

**Comment by createme** [comment]
why do you need it?

**Comment by crutchcorn** [comment]
Credit and copyright

**Comment by danielhickman** [comment]
@createme We would've liked to have it but we changed our copyright to include our names so we could better enforce it. If you're not comfortable giving us it, don't worry :D

**Comment by createme** [comment]
Im just doing this out of fun as a side project thats why don´t really want to put my real name on it (As long as this isn´t problem).

**Comment by danielhickman** [comment]
Sure that's fine. Thanks for your support.

**Pull request merged**
