### PR TITLE
Added some icons by Alex Mueller (Lollydrop)! Thanks Alex Mueller (Lollydrop)!

### PR DESCRIPTION
**Pull request by autocontribute**

### CODE REVIEW

**Comment by danielhickman** [comment]
@crutchcorn I'm getting the icon via GDrive. Could you figure why this happened? It seems like it counted the chmod and chown I recently did on the server.

**Comment by crutchcorn** [comment]
Well duh it's going to count chmoding and chowning! That's modifying files too you know!

**Comment by autocontribute** [comment]
Is there a way to prevent it? It's a pain to being able to edit the files.

**Comment by crutchcorn** [comment]
The only way to prevent that is not not chown and chmod files. ;P

**Pull request closed without merging**
