### PR TITLE
Added my first icons (Katacarbix)

### PR DESCRIPTION
**Pull request by katacarbix**
These are my first icons for the MaterialOS Icon Pack. I will be contributing more in the future.

### CODE REVIEW

**Comment by adueppen** [comment]
One thing I am seeing with the icons is that the US Bank icon is using overlapping long shadows for the letters and it doesn't really work too well. You might want to try merging them. Other than that, they look pretty good.

**Comment by katacarbix** [comment]
I noticed it did that when I saved it but the raster looks how I intended. I think I fixed it on my local machine so I'll update that soon.

**Comment by katacarbix** [comment]
Wait it looks fine in the most recent commit, are you sure that's what you're looking at?

**Comment by crutchcorn** [comment]
I love them. I apologize for my silence. Adding them now!

**Comment by katacarbix** [comment]
Thank you!! I cancelled my CC subscription, but I'll still keep making icons.

**Pull request merged**
