### PR TITLE
Update Google Play Badge

### PR DESCRIPTION
**Pull request by FionaHagen**

### CODE REVIEW

**Comment by adueppen** [comment]
It might be better to use https://play.google.com/intl/en_us/badges/images/badge_new.png as it's hosted on Google's servers. There's also a large version available here: https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png

**Comment by FionaHagen** [comment]
OK, I can change that if you prefer that.
Can you please explain why it would be better to use the badge from the Google servers? I host the badge on GitHub because the whole repo is on GitHub too and Google should not be able to track the visitors of this repo. Thank you.

**Comment by adueppen** [comment]
Sorry for the late response, I think it would most likely be better to use the image on the Google servers since the URL I gave will (probably) get updated in the event that they change the design in the future, so it should make it easier to keep it updated.

**Comment by FionaHagen** [comment]
OK, I will change that.

**Pull request merged**
