### PR TITLE
Added most icons from Oko

### PR DESCRIPTION
**Pull request by adueppen**
Here are most of the icons that are in the Oko repo right now that I feel are worth contributing to a larger project. Feel free to point out any issues you see.

### CODE REVIEW

**Comment by Anonymas** [comment]
@crutchcorn I think this one should be merged straight away?

**Comment by crutchcorn** [comment]
You can absolutely merge. I will have to check it when possible. In SF
right now

**Comment by adueppen** [comment]
@crutchcorn Yay thanks!

**Comment by crutchcorn** [comment]
Just wait... ;)

**Pull request closed without merging**
